# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
